runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(?!dist)  # Skip any files not in the dist folder

handlers:
- url: /
  static_files: dist/hw8-client/index.html
  upload: dist/hw8-client/index.html
- url: /
  static_dir: dist/hw8-client

